repos:
  - repo: https://github.com/dnephin/pre-commit-golang
    rev: v0.5.1
    hooks:
      - id: go-build
      - id: go-fmt
      - id: go-vet
      - id: go-lint
      - id: go-imports
      - id: go-cyclo
        args: [-over=15]

  - repo: local
    hooks:
      - id: embed-examples
        name: embed-examples
        entry: npx embedme --verify README.md
        language: system
        pass_filenames: false
